Repository tanishaness/SPROCTOR, pull requests merged in 2024-10, with the labels that each got.

#25 feat : Change the graph for a better visualization #22
  Backend/SQLFILE.sql
  Backend/graph.py
  heatmap_combined_20241009_144503.png
Labels: enhancement, help wanted, gssoc-ext, level3, hacktoberfest-accepted

#26 Adding Peer Comparison Tool.
  Backend/peer_comparison_tool.py
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted

#46 Enhancing Offline Capabilities of S-Proctor for Real-Time Cheating Detection
  Backend/Offline-capabilities/ML-Model-Optimisation.py
  Backend/Offline-capabilities/local-storage.py
  Backend/Offline-capabilities/processing-data.py
  Backend/Offline-capabilities/readme.md
  Backend/Offline-capabilities/resource-management.py
  Backend/Offline-capabilities/video-processing.py
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted

#52 contributor page added.
  GUI/active.html
  GUI/copypaste.html
  GUI/windowClose.html
  contributor/contributor.css
  contributor/contributor.html
  contributor/contributor.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#53 Made the modification
  Backend/Dataset/feedback.html
  GUI/active.html
  GUI/copypaste.html
  GUI/windowClose.html
Labels: gssoc-ext, level3, hacktoberfest-accepted

#55 added tensorflow library in requirements.txt because it is missing
  requirements.txt
Labels: gssoc-ext, level1, hacktoberfest-accepted

#61 Automated project structure updation using github workflows, python scripts and action bot
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  PROJECT_STRUCTURE.md
  ReadMe.md
  repo_structure.txt
Labels: gssoc-ext, level2, hacktoberfest-accepted

#60 Github actions for more connectivity!
  .github/workflows/issue_open_close.yml
  .github/workflows/pr_merge.yaml
  .github/workflows/pr_raise.yml
  .github/workflows/pt_checker.yaml
Labels: gssoc-ext, level3, hacktoberfest-accepted

#63 Add calender app to the app || Integrated With Google Calender
  calenderApp/calender.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#64 Added Stargazers and Forkers section to readme.md
  ReadMe.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#74 Enhancement of login page FIXES #66
  Backend/login.py
  PROJECT_STRUCTURE.md
  Userdb.sql
  login.py
  repo_structure.txt
  templates/login.html
Labels: gssoc-ext, level3, hacktoberfest-accepted
