Repository tanishaness/SPROCTOR, pull requests merged in 2024-11, with the labels that each got.

#81 Update object_detection.py
  Backend/object_detection.py
Labels: gssoc-ext, level3, hacktoberfest-accepted

#87 Update issue_open_close.yml
  .github/workflows/issue_open_close.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#84 Enhance Peer Comparison Tool with PCI, CSV Reporting, and Dynamic Tracking
  Backend/peer_comparison_tool.py
Labels: gssoc-ext, level3, hacktoberfest-accepted

#88 added the whole frontend for the SPROCTOR
  Backend/proctor_core.py
  Backend/run.py
  PROJECT_STRUCTURE.md
  repo_structure.txt
  requirements.txt
Labels: gssoc-ext, level3, hacktoberfest-accepted

#93 Update object_detection.py
  Backend/object_detection.py
Labels: gssoc-ext, level2, hacktoberfest-accepted

#91 Add Tutorials Page for Guided Learning and Feature Exploration
  __pycache__/tutorial/tutorial.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#105 Updated calender.html
  calenderApp/calender.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#102 added (Api)
  Backend/proctor_api.py
  Backend/proctor_core.py
  Backend/run.py
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted

#104 Model training
  Backend/model_training.py
  Backend/proctor_core.py
  Backend/run.py
  Backend/train.py
Labels: gssoc-ext, level3, hacktoberfest-accepted

#97 Configurable Amplitude Threshold #90
  Backend/audio.py
Labels: gssoc-ext, level3, hacktoberfest-accepted

#96 Create SECURITYPolicy .md
  SECURITYPOLICY.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#118 Functionality to track multiple students
  Backend/detection.py
  Backend/proctor_api.py
  Backend/student_tracker.py
  PROJECT_STRUCTURE.md
  repo_structure.txt
Labels: gssoc-ext, level3, hacktoberfest-accepted
